### ISSUE TITLE
关注后及时更新关注数缓存

### ISSUE THREAD

**Issue by Dkaishu** [chafan-dev/roadmap#8]
在我的个人页面里，显示的【关注了34个人】与【关注的人】tab页里人数不符，实际应该有100多。

**Comment by Dkaishu** [comment]
短时间内我关注了几十人，显示的关注人数（似乎）并没有增加。

**Comment by izgzhen** [comment]
这个是缓存的，会过一段时间才生效，如无其他问题目前先关闭这个 issue 了，谢谢！
